FROM php:7.1-alpine

# Uncomment the furhter line to add needed extension(s)
# RUN docker-php-ext-install iconv

# Uncomment the furhter line to add and enable a needed pecl extension(s)
# RUN pecl install memcached && docker-php-ext-enable memcached

VOLUME ["/app"]
WORKDIR /app
